name: Build Firmware
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Burnmaster-Firmware
        uses: actions/checkout@v3
        with:
          path: Burnmaster-Firmware
          
      - name: Install EmeddedStudio
        run: |
            wget https://www.segger.com/downloads/embedded-studio/Setup_EmbeddedStudio_ARM_v622a_linux_x64.tar.gz
            tar -xvf Setup_EmbeddedStudio_ARM_v622a_linux_x64.tar.gz
            cd arm_segger_embedded_studio_v622a_linux_x64/
            sudo ./install_segger_embedded_studio --minimal-install --accept-license --copy-files-to .
        
      - name: Compile Firmware
        run: |
            cd arm_segger_embedded_studio_v622a_linux_x64/bin
            ./emBuild -config "Debug" ${{ github.workspace }}//Burnmaster-Firmware/CartReaderApp/GDCartReader.emProject
          
      - uses: actions/upload-artifact@v3
        with:
          name: Burnmaster-Firmware
          path: ${{ github.workspace }}//Burnmaster-Firmware/CartReaderApp/Output/Debug/Exe/GDCartReader.bin
